// Convert image to pure black and white (no grayscale)
export const convertToBlackAndWhite = (
  imageData: ImageData,
  threshold: number = 128
): ImageData => {
  const data = new Uint8ClampedArray(imageData.data);
  
  for (let i = 0; i < data.length; i += 4) {
    const r = data[i];
    const g = data[i + 1];
    const b = data[i + 2];
    
    // Calculate luminance
    const luminance = 0.299 * r + 0.587 * g + 0.114 * b;
    
    // Apply threshold
    const value = luminance >= threshold ? 255 : 0;
    
    data[i] = value;
    data[i + 1] = value;
    data[i + 2] = value;
  }
  
  return new ImageData(data, imageData.width, imageData.height);
};

// Default Zebra label limits at 203 DPI (8 dots/mm) for a 100mm x 204mm label.
export const LABEL_MAX_WIDTH_PX = 812;
export const LABEL_MAX_HEIGHT_PX = 1656;

/**
 * Ensures the source image fits within the label boundary.
 * - If the image is smaller, it is centered on a white canvas of its own size
 *   (no upscaling, no tiling/pattern).
 * - If the image exceeds the maximum dimensions, it is proportionally scaled
 *   down to fit within LABEL_MAX_WIDTH_PX x LABEL_MAX_HEIGHT_PX and centered.
 * The returned ImageData has exactly the dimensions used for the GRF, so the
 * conversion loop will never duplicate the image horizontally.
 */
export const clampToLabelSize = (
  imageData: ImageData,
  maxWidth: number = LABEL_MAX_WIDTH_PX,
  maxHeight: number = LABEL_MAX_HEIGHT_PX
): ImageData => {
  const srcW = imageData.width;
  const srcH = imageData.height;

  if (srcW <= maxWidth && srcH <= maxHeight) {
    return imageData;
  }

  // Compute scale (only down-scale, never up-scale).
  const scale = Math.min(1, maxWidth / srcW, maxHeight / srcH);
  const drawW = Math.max(1, Math.floor(srcW * scale));
  const drawH = Math.max(1, Math.floor(srcH * scale));

  // Final canvas size = drawn size (no padding/tiling). This guarantees
  // bytesPerRow = ceil(width/8) matches the actual pixel width.
  const canvas = document.createElement('canvas');
  canvas.width = drawW;
  canvas.height = drawH;
  const ctx = canvas.getContext('2d');
  if (!ctx) return imageData;

  // White background (any padding bits will be 0 = white in GRF).
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, drawW, drawH);

  // Render the source ImageData via a temporary canvas to allow scaling.
  const srcCanvas = document.createElement('canvas');
  srcCanvas.width = srcW;
  srcCanvas.height = srcH;
  const srcCtx = srcCanvas.getContext('2d');
  if (!srcCtx) return imageData;
  srcCtx.putImageData(imageData, 0, 0);

  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(srcCanvas, 0, 0, srcW, srcH, 0, 0, drawW, drawH);

  return ctx.getImageData(0, 0, drawW, drawH);
};

// Convert image to GRF format for Zebra printers
export const convertToGRF = (
  imageData: ImageData,
  name: string = "IMAGE"
): string => {
  const width = imageData.width;
  const height = imageData.height;
  // Bytes per printed row — strictly based on the image width.
  const bytesPerRow = Math.ceil(width / 8);
  const totalBytes = bytesPerRow * height;

   const rows = new Array<string>(height);

  // Row-by-row scan. Each row terminates exactly at `width` and the
  // remaining bits of the last byte are left as 0 (white space).
  for (let y = 0; y < height; y++) {
    const rowStart = y * width * 4;
     const rowBytes = new Array<string>(bytesPerRow);
    for (let byteIndex = 0; byteIndex < bytesPerRow; byteIndex++) {
      let byte = 0;
      const baseX = byteIndex * 8;
      const bitsThisByte = Math.min(8, width - baseX); // <8 on the last byte if width % 8 !== 0
      for (let bit = 0; bit < bitsThisByte; bit++) {
        const pixelIndex = rowStart + (baseX + bit) * 4;
        const r = imageData.data[pixelIndex];
        const g = imageData.data[pixelIndex + 1];
        const b = imageData.data[pixelIndex + 2];
        const luminance = 0.299 * r + 0.587 * g + 0.114 * b;
        if (luminance < 128) {
          byte |= (1 << (7 - bit));
        }
      }
       rowBytes[byteIndex] = byte.toString(16).padStart(2, '0').toUpperCase();
    }
     rows[y] = rowBytes.join('');
  }

   const safeName = name.toUpperCase().replace(/[^A-Z0-9_]/g, '').slice(0, 8) || 'IMAGE';
   const totalBytesText = String(totalBytes).padStart(Math.max(5, String(totalBytes).length), '0');
   const bytesPerRowText = String(bytesPerRow).padStart(Math.max(3, String(bytesPerRow).length), '0');

   // Use the same classic ~DG layout generated by Zebra tools: one header line
   // followed by exactly one hex row per raster line.
   return `~DG${safeName},${totalBytesText},${bytesPerRowText},${rows.join('\n')}`;
};

// Raster image with different photometry options
export type Photometry = 'uncompressed' | 'rgb-palette' | 'rgb';
export type Compression = 'uncompressed';

export interface RasterOptions {
  photometry: Photometry;
  compression?: Compression;
  width: number;
  height: number;
}

export const rasterImage = (
  imageData: ImageData,
  options: RasterOptions
): { imageData: ImageData; rawData: Uint8Array } => {
  const { photometry, width, height } = options;

  const newWidth = width;
  const newHeight = height;

  const outputData = new Uint8ClampedArray(newWidth * newHeight * 4);
  const rawData: number[] = [];

  if (photometry === 'uncompressed' || photometry === 'rgb') {
    // Both store full RGB; 'rgb' label is the photometric interpretation tag.
    for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        const srcIndex = (y * width + x) * 4;
        const dstIndex = (y * newWidth + x) * 4;
        outputData[dstIndex] = imageData.data[srcIndex];
        outputData[dstIndex + 1] = imageData.data[srcIndex + 1];
        outputData[dstIndex + 2] = imageData.data[srcIndex + 2];
        outputData[dstIndex + 3] = 255;
        rawData.push(imageData.data[srcIndex]);
        rawData.push(imageData.data[srcIndex + 1]);
        rawData.push(imageData.data[srcIndex + 2]);
      }
    }
  } else {
    // RGB Palette - indexed
    const palette: Map<string, number> = new Map();
    let paletteIndex = 0;
    for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        const srcIndex = (y * width + x) * 4;
        const r = imageData.data[srcIndex];
        const g = imageData.data[srcIndex + 1];
        const b = imageData.data[srcIndex + 2];
        const colorKey = `${r},${g},${b}`;
        if (!palette.has(colorKey)) palette.set(colorKey, paletteIndex++);
        const dstIndex = (y * newWidth + x) * 4;
        outputData[dstIndex] = r;
        outputData[dstIndex + 1] = g;
        outputData[dstIndex + 2] = b;
        outputData[dstIndex + 3] = 255;
        rawData.push(palette.get(colorKey)!);
      }
    }
  }

  return {
    imageData: new ImageData(outputData, newWidth, newHeight),
    rawData: new Uint8Array(rawData),
  };
};

// Download helpers
export const downloadFile = (content: string | Blob, filename: string, type: string) => {
  const blob = content instanceof Blob ? content : new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const canvasToBlob = (canvas: HTMLCanvasElement): Promise<Blob> => {
  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob) resolve(blob);
      else reject(new Error('Failed to create blob'));
    }, 'image/png');
  });
};

export const downloadCanvasAsImage = async (canvas: HTMLCanvasElement, filename: string) => {
  const blob = await canvasToBlob(canvas);
  downloadFile(blob, filename, 'image/png');
};
